# Generated by Django 4.1.4 on 2022-12-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Questionaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('SINGLE', 'Single'), ('MULTIPLE', 'Multiple')], max_length=10)),
                ('answers', models.ManyToManyField(related_name='question_answers', to='tests.answers')),
                ('options', models.ManyToManyField(related_name='question_options', to='tests.options')),
            ],
        ),
    ]
