# Generated by Django 4.1.4 on 2022-12-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaries',
            name='question_type',
            field=models.CharField(choices=[('Single', 'SINGLE'), ('Multiple', 'MULTIPLE')], max_length=10),
        ),
    ]
