# Generated by Django 4.1.4 on 2022-12-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_questionariesparent_rename_questions_test_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
