# Generated by Django 4.1.4 on 2022-12-15 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_test_exam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions_type',
            field=models.CharField(choices=[('Single', 'SINGLE'), ('Multiple', 'MULTIPLE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.questionariesparent'),
        ),
    ]
