# Generated by Django 4.1.4 on 2022-12-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_test_questions_type_alter_test_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='questions_type',
        ),
        migrations.AddField(
            model_name='questionariesparent',
            name='questions_type',
            field=models.CharField(choices=[('Single', 'SINGLE'), ('Multiple', 'MULTIPLE')], max_length=20, null=True),
        ),
    ]
