# Generated by Django 4.1.4 on 2022-12-15 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_remove_test_questions_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionaries',
            name='question_type',
        ),
    ]
