# Generated by Django 4.1.4 on 2022-12-15 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0011_rename_questions_cont_test_questions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscoresscores',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
