# Generated by Django 4.1.4 on 2022-12-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_testscoresscores_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaries',
            name='answers',
            field=models.ManyToManyField(related_name='question_answers', to='tests.options'),
        ),
    ]
