# Generated by Django 4.1.4 on 2022-12-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_alter_questionaries_answers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
